name: Build & Push Rust Image to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          cd games/rust
          docker build -t ghcr.io/${{ github.repository_owner }}/rust-staging:latest .

      - name: Push to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/rust-staging:latest
